app:
  #web port
  port: 3001
  uk: rust.dsf.rust_admin
  name: rust_admin
  #debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug，rbatis也需移除"debug_mode"
  #Debug mode, true for outputting console log, false for only outputting file log. Debug mode should be turned off in production, and "debug_mode" should also be removed from rbatis.
  debug: true

login:
  #登陆失败拒绝策略，重试次数限制(0次无限制)
  #Login failure rejection policy, retry limit (0 times for no limit)
  login_fail_retry: 3
  #登陆失败重试次数限制超过后提示的等待时间（秒）
  #Waiting time for login failure retry limit exceeded (in seconds)
  login_fail_retry_wait_sec: 30
  #接口白名单（免登陆直接访问）
  #Interface whitelist (direct access without login)
  white_list_api:
    - "/"
    - "/admin/sys_login"
    - "/admin/captcha"

database:
  url: "mysql://root:123456@localhost:3306/test"
  logic_column: "del"
  logic_un_deleted: 0
  logic_deleted: 1

log:
  dir: "logs"
  #日志分割尺寸-单位KB,MB,GB
  #Log rotation size - unit: KB, MB, GB
  log_temp_size: "100MB"
  #日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
  #Log rolling retention - keep all: All, keep by time (in seconds): KeepTime(i64), keep by version: KeepNum(i64)
  log_rolling_type: "KeepNum(20)"
  #日志等级: off,info,error,warn,debug,trace
  #Log level: off, info, error, warn, debug, trace
  log_level: "info"
  #日志通道长度，null为无界队列，非null为有界队列（性能好）
  #Log channel length, null for unbounded queue, non-null for bounded queue (better performance)
  log_chan_len: 100000

cache:
  #redis or mem
  cache_type: redis
  redis_url: "redis://127.0.0.1:6379"





